services:
  - type: web
    name: product-catalog-api
    env: docker
    dockerfilePath: ./dotnet-migrated/ProductCatalog.Api/Dockerfile
    dockerContext: ./dotnet-migrated/ProductCatalog.Api
    plan: free
    healthCheckPath: /api/products
